<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="4" passed="2">
  <reporter-output>
    <line>
      <![CDATA[<br><img src='C:\Users\Android4\Desktop\SCREENSHOTForManufacture\SCREENSHOTLogin.png' height='400' width='400' >]]>
    </line>
    <line>
      <![CDATA[<br><img src='C:\Users\Android4\Desktop\SCREENSHOTForManufacture\SCREENSHOTTestvehicle.png' height='400' width='400' >]]>
    </line>
  </reporter-output>
  <suite name="Test - Suite" duration-ms="20752" started-at="2018-11-28T09:59:49Z" finished-at="2018-11-28T10:00:10Z">
    <groups>
    </groups>
    <test name="RO" duration-ms="20752" started-at="2018-11-28T09:59:49Z" finished-at="2018-11-28T10:00:10Z">
      <class name="ROAutomation.LaunchApp">
        <test-method status="PASS" signature="Login()[pri:0, instance:ROAutomation.LaunchApp@724af044]" name="Login" duration-ms="17900" started-at="2018-11-28T15:29:49Z" description="Login Page" finished-at="2018-11-28T15:30:07Z">
          <reporter-output>
            <line>
              <![CDATA[<br><img src='C:\Users\Android4\Desktop\SCREENSHOTForManufacture\SCREENSHOTLogin.png' height='400' width='400' >]]>
            </line>
          </reporter-output>
        </test-method> <!-- Login -->
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:ROAutomation.LaunchApp@724af044]" name="beforeClass" is-config="true" duration-ms="0" started-at="2018-11-28T15:29:49Z" finished-at="2018-11-28T15:29:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="FAIL" signature="TestManufacturer()[pri:0, instance:ROAutomation.LaunchApp@724af044]" name="TestManufacturer" duration-ms="2202" started-at="2018-11-28T15:30:08Z" description="Log into Application" finished-at="2018-11-28T15:30:10Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Manufacturer Added Successfully!] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Manufacturer Added Successfully!] but found []
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at ROAutomation.Manufacture.AddManufacturer(Manufacture.java:50)
	at ROAutomation.LaunchApp.TestManufacturer(LaunchApp.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestManufacturer -->
        <test-method status="PASS" signature="Testvehicle()[pri:0, instance:ROAutomation.LaunchApp@724af044]" name="Testvehicle" duration-ms="2" started-at="2018-11-28T15:30:10Z" description="Log into Application" finished-at="2018-11-28T15:30:10Z">
          <reporter-output>
            <line>
              <![CDATA[<br><img src='C:\Users\Android4\Desktop\SCREENSHOTForManufacture\SCREENSHOTTestvehicle.png' height='400' width='400' >]]>
            </line>
          </reporter-output>
        </test-method> <!-- Testvehicle -->
      </class> <!-- ROAutomation.LaunchApp -->
      <class name="ROAutomation.vehicle">
        <test-method status="FAIL" signature="ownernamevalidation()[pri:0, instance:ROAutomation.vehicle@548a9f61]" name="ownernamevalidation" duration-ms="2" started-at="2018-11-28T15:30:10Z" description="validation" finished-at="2018-11-28T15:30:10Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at pageObjects.Vehicle.vehicleMenu(Vehicle.java:11)
	at ROAutomation.vehicle.ownernamevalidation(vehicle.java:179)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ownernamevalidation -->
      </class> <!-- ROAutomation.vehicle -->
    </test> <!-- RO -->
  </suite> <!-- Test - Suite -->
</testng-results>
